export enum GameStatuses {
  CREATION = 'CREATION',
  JOINING = 'JOINING',
  PLAYING = 'PLAYING',
  END_ROUND = 'END_ROUND',
  EVALUATION = 'EVALUATION',
  SCORE_VIEWING = 'SCORE_VIEWING',
  END_QUIZ = 'END_QUIZ',
}
