import { ReactNode } from 'react';
import { Stack, StackProps } from '@chakra-ui/react';
import Head from 'next/head';
import { STACK_SPACING } from '../../../constants';

export interface Props extends StackProps {
  children: ReactNode;
}

export function Wrapper({ children, ...props }: Props) {
  return (
    <>
      <Head>
        <title>Pub quiz app</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <Stack py={16} px={8} spacing={STACK_SPACING} {...props}>
        {children}
      </Stack>
    </>
  );
}
