import Head from 'next/head';
import { Box, Flex } from '@chakra-ui/react';
import Header from '../components/headers/header';
import SubHeader from '../components/headers/sub-header';
import SubTitle from '../components/headers/sub-title';
import PrimaryButton from '../components/buttons/primary-button';
import SecondaryButton from '../components/buttons/secondary-button';
import { useRouter } from 'next/router';
import DummyPeople from '../components/images/dummy-people';
import * as React from 'react';
import { MainPageWrapper } from '../components/wrappers/main-page-wrapper';
import { trpc } from '../utils/trcp';

export default function Home() {
  // This is just an example how to call tRPC
  // if you need lazily call the query set enabled to false
  // and use refetch function
  const { data, refetch } = trpc.hello.useQuery(
    { text: 'Gww' },
    { enabled: false },
  );

  const router = useRouter();

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <MainPageWrapper>
        <Box mb={14}>
          <Flex alignItems="center" flexDirection="column" textAlign="center">
            <Header>Hello there</Header>
            <Box my={10}>
              <DummyPeople />
            </Box>
            <SubHeader size="lg" mb="4">
              Looks like you’re ready to have a great time.
            </SubHeader>
            <SubTitle>
              Time to enter your quiz’s PIN and let’s get started.
            </SubTitle>
          </Flex>
        </Box>
        <PrimaryButton onClick={() => router.push('add-pin')} w="100%" mb={2}>
          Enter PIN
        </PrimaryButton>
        <SecondaryButton w="100%">Admin dashboard</SecondaryButton>
      </MainPageWrapper>
    </>
  );
}
