import Head from 'next/head';
import styles from '../styles/Home.module.css';
import {
  Heading,
  Button,
  Modal,
  ModalOverlay,
  ModalBody,
  ModalHeader,
  ModalContent,
  ModalFooter,
  ModalCloseButton,
  Stack,
  PinInputField,
  HStack,
  PinInput,
  Center,
  Text,
  Box,
  Flex,
} from '@chakra-ui/react';
import { useState } from 'react';
export default function Home() {
  const [modalStatus, changeModalStatus] = useState<boolean>(false);
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <main className={styles.main}>
        <Box mb={98}>
          <Flex alignItems="center" flexDirection="column">
            <Heading as="h1" size="3xl" color="green.100" mb={200}>
              Hello there
            </Heading>
            <Heading as="h2" textAlign="center" mb={2}>
              Looks like you’re ready to have a great time.
            </Heading>
            <Text color="gray.400" align="center">
              Time to enter your quiz’s PIN and let’s get started.
            </Text>
          </Flex>
        </Box>
        <Button
          w="100%"
          onClick={() => changeModalStatus(true)}
          color="white"
          bgColor="green.100"
          mb={2}
        >
          Enter PIN
        </Button>
        <Button
          variant="outline"
          borderColor="green.100"
          w="100%"
          color="green.100"
        >
          Admin dashboard
        </Button>
        <Modal isOpen={modalStatus} onClose={() => changeModalStatus(false)}>
          <ModalOverlay />
          <ModalContent>
            <ModalHeader>Login</ModalHeader>
            <ModalCloseButton />
            <ModalBody>
              <Center>
                <Stack>
                  <Heading as="h3" size="md">
                    Please enter PIN of the game you want to enter:
                  </Heading>
                  <Center>
                    <HStack>
                      <PinInput type="alphanumeric">
                        <PinInputField />
                        <PinInputField />
                        <PinInputField />
                        <PinInputField />
                      </PinInput>
                    </HStack>
                  </Center>
                </Stack>
              </Center>
            </ModalBody>
            <ModalFooter>
              <Button
                colorScheme="blue"
                mr={3}
                onClick={() => changeModalStatus(false)}
              >
                Join
              </Button>
              <Button onClick={() => changeModalStatus(false)} variant="ghost">
                Close
              </Button>
            </ModalFooter>
          </ModalContent>
        </Modal>
      </main>
    </>
  );
}
