import Head from 'next/head';
import styles from '../styles/Home.module.css';
import {
  Heading,
  Button,
  Modal,
  ModalOverlay,
  ModalBody,
  ModalHeader,
  ModalContent,
  ModalFooter,
  ModalCloseButton,
  Stack,
  PinInputField,
  HStack,
  PinInput,
  Center,
} from '@chakra-ui/react';
import { useState } from 'react';
export default function Home() {
  const [modalStatus, changeModalStatus] = useState<boolean>(false);
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <main className={styles.main}>
        <Heading as="h1" size="3xl" noOfLines={1}>
          Welcome to Pub Quiz 💻
        </Heading>
        <Button onClick={() => changeModalStatus(true)}>Join!</Button>
        <Button>Create!</Button>
        <Modal isOpen={modalStatus} onClose={() => changeModalStatus(false)}>
          <ModalOverlay />
          <ModalContent>
            <ModalHeader>Login</ModalHeader>
            <ModalCloseButton />
            <ModalBody>
              <Center>
                <Stack>
                  <Heading as="h3" size="md">
                    Please enter PIN of the game you want to enter:
                  </Heading>
                  <Center>
                    <HStack>
                      <PinInput type="alphanumeric">
                        <PinInputField />
                        <PinInputField />
                        <PinInputField />
                        <PinInputField />
                      </PinInput>
                    </HStack>
                  </Center>
                </Stack>
              </Center>
            </ModalBody>
            <ModalFooter>
              <Button
                colorScheme="blue"
                mr={3}
                onClick={() => changeModalStatus(false)}
              >
                Close
              </Button>
              <Button onClick={() => changeModalStatus(false)} variant="ghost">
                Join
              </Button>
            </ModalFooter>
          </ModalContent>
        </Modal>
      </main>
    </>
  );
}
